language: rust
rust:
- stable
- beta
- nightly
- 1.34.0
matrix:
  allow_failures:
  - rust: nightly
sudo: required
addons:
  apt:
    packages:
    - postfix
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
    - cmake
    - gcc
    - binutils-dev
    - libiberty-dev
before_script:
- smtp-sink 2525 1000&
- sudo chgrp -R postdrop /var/spool/postfix/maildrop
script:
- cargo test --verbose --all --all-features
- cargo test --no-default-features --features=transport-smtp
after_success:
- ./.build-scripts/codecov.sh
- '[ "$TRAVIS_RUST_VERSION" = "stable" ] && [ "$TRAVIS_BRANCH" = "v0.9.x" ] && [ $TRAVIS_PULL_REQUEST = false ] && ./.build-scripts/site-upload.sh'
