language: rust

rust:
- stable
- beta
- nightly
- 1.18.0

matrix:
  allow_failures:
    - rust: nightly

sudo: required

cache:
  directories:
  - target/debug/deps
  - target/debug/build
  - target/release/deps
  - target/release/build

addons:
  apt:
    packages:
    - postfix

before_script:
  - smtp-sink 2525 1000&
  - sudo chgrp -R postdrop /var/spool/postfix/maildrop

script:
  - cargo test --verbose --manifest-path lettre/Cargo.toml --no-default-features
  - cargo test --verbose --manifest-path lettre/Cargo.toml
  - cargo test --verbose --manifest-path lettre_email/Cargo.toml

env:
  global:
    secure: "MaZ3TzuaAHuxmxQkfJdqRfkh7/ieScJRk0T/2yjysZhDMTYyRmp5wh/zkfW1ADuG0uc4Pqsxrsh1J9SVO7O0U5NJA8NKZi/pgiL+FHh0g4YtlHxy2xmFNB5am3Kyc+E7B4XylwTbA9S8ublVM0nvX7yX/a5fbwEUInVk2bA8fpc="
