[book]
title = "Lettre documentation"
authors = ["Alexis Mousset"]
description = "The user documentation of the Lettre crate."

[output.html]
default-theme = "Ayu"
no-section-label = true

[output.linkcheck]
